import os
import requests

def check_profile(url, name):
    response = requests.get(url)
    if response.status_code == 200:
        return True
    elif response.status_code == 404:
        return False
    else:
        response.raise_for_status()

# Clear console screen based on the operating system
if os.name == 'nt':
    os.system('cls')  # For Windows
else:
    os.system('clear')  # For Linux and macOS

# Example usage
websites = [
    'https://www.linkedin.com/in/{name}',
    'https://twitter.com/{name}',
    'https://www.facebook.com/{name}',
    'https://www.instagram.com/{name}',
    'https://www.pinterest.com/{name}',
    'https://www.snapchat.com/add/{name}',
    'https://www.tiktok.com/@{name}',
    'https://www.reddit.com/user/{name}',
    'https://www.tumblr.com/search/{name}',
    'https://www.youtube.com/{name}',
    'https://web.whatsapp.com/{name}',
    'https://www.wechat.com/{name}',
    'https://telegram.me/{name}',
    'https://www.viber.com/en/{name}',
    'https://www.flickr.com/people/{name}',
    'https://www.vine.co/{name}',
    'https://www.periscope.tv/{name}',
    'https://soundcloud.com/{name}',
    'https://www.meetup.com/members/{name}',
    'https://www.quora.com/profile/{name}',
    'https://plus.google.com/{name}',
    'https://myspace.com/{name}',
    'https://www.hi5.com/{name}',
    'https://www.orkut.com/{name}',
    'https://www.friendster.com/{name}',
    'https://www.xing.com/profile/{name}',
    'https://vk.com/{name}',
    'https://www.ok.ru/profile/{name}',
    'https://www.livejournal.com/profile?userid={name}',
    'https://medium.com/@{name}',
    'https://wordpress.com/{name}',
    'https://{name}.blogspot.com/',
    'https://ghost.org/{name}',
    'https://www.minds.com/{name}',
    'https://gab.com/{name}',
    'https://parler.com/profile/{name}',
    'https://mastodon.social/{name}',
    'https://ello.co/{name}',
    'https://www.swarmapp.com/{name}',
    'https://foursquare.com/{name}',
    'https://www.yelp.com/user_details?userid={name}',
    'https://www.tripadvisor.com/members/{name}',
    'https://www.zomato.com/{name}',
    'https://www.goodreads.com/{name}',
    'https://www.last.fm/user/{name}',
    'https://bandcamp.com/{name}',
    'https://www.behance.net/{name}',
    'https://dribbble.com/{name}',
    'https://www.deviantart.com/{name}',
    'https://www.twitch.tv/{name}',
    'https://mixer.com/{name}',
    'https://discordapp.com/users/{name}',
    'https://www.weibo.com/{name}',
    'https://www.douban.com/people/{name}',
    'https://renren.com/{name}',
    'https://17.live/live/{name}',
    'https://www.qq.com/{name}',
    'https://line.me/R/ti/p/{name}',
    'https://www.kakaocorp.com/service/KakaoTalk',
    'https://nid.naver.com/user2/VRRCheck.nhn?m=always',
    'https://weheartit.com/{name}',
    'https://www.stumbleupon.com/stumbler/{name}',
    'https://delicious.com/{name}',
    'https://www.slideshare.net/{name}',
    'https://www.scribd.com/{name}',
    'https://www.academia.edu/{name}',
    'https://{name}.xanga.com/',
    'https://www.tagged.com/{name}',
    'https://www.bebo.com/{name}',
    'https://www.fotolog.com/{name}',
    'https://www.gaiaonline.com/profiles/{name}',
    'https://www.ning.com/people/{name}',
    'https://{name}.xanga.com/',
    'https://www.tribe.net/people/{name}',
    'https://www.blackplanet.com/{name}',
    'https://miiverse.nintendo.net/users/{name}',
    'https://www.fotki.com/{name}',
    'https://www.ravelry.com/people/{name}',
    'https://www.nextdoor.com/profile/{name}',
    'https://mixi.jp/show_profile.pl?id={name}',
    'https://www.caffeine.tv/{name}',
    'https://byte.co/{name}',
    'https://www.lomography.com/homes/{name}',
    'https://www.wayn.com/profiles/{name}',
    'https://www.viadeo.com/{name}',
    'https://renren.com/{name}',
    'https://www.fotki.com/{name}',
    'https://www.dailymotion.com/{name}',
    'https://vine.co/u/{name}',
    'https://www.vero.co/{name}',
    'https://aminoapps.com/c/{name}',
    'https://www.asmallworld.com/members/{name}',
    'https://www.vero.co/{name}',
    'https://weibo.com/{name}',
    'https://www.douban.com/people/{name}',
    'https://renren.com/{name}',
    'https://mewe.com/i/{name}',
    'https://www.yubo.live/profile/{name}',
    'https://www.triller.co/@{name}',
    'https://about.me/{name}',
    'https://angel.co/{name}',
    'https://www.artstation.com/{name}',
    'https://ask.fm/{name}',
    'https://badoo.com/en/{name}',
    'https://bitbucket.org/{name}',
    'https://www.buzzfeed.com/{name}',
    'https://www.canva.com/{name}',
    'https://www.couchsurfing.com/people/{name}',
    'https://www.crunchyroll.com/user/{name}',
    'https://www.dailykos.com/user/{name}',
    'https://www.etsy.com/people/{name}',
    'https://evernote.com/{name}',
    'https://flipboard.com/@{name}',
    'https://www.fotki.com/{name}',
    'https://gitlab.com/{name}',
    'https://www.goodreads.com/{name}',
    'https://gravatar.com/{name}',
    'https://www.houzz.com/user/{name}',
    'https://imgur.com/user/{name}',
    'https://www.instructables.com/member/{name}',
    'https://issuu.com/{name}',
    'https://ko-fi.com/{name}',
    'https://lainchan.org/{name}',
    'https://www.last.fm/user/{name}',
    'https://letterboxd.com/{name}',
    'https://www.liveleak.com/c/{name}',
    'https://myspace.com/{name}',
    'https://www.newgrounds.com/user/{name}',
    'https://www.patreon.com/{name}',
    'https://www.pexels.com/@{name}',
    'https://photobucket.com/user/{name}',
    'https://pixabay.com/users/{name}',
    'https://www.playbuzz.com/{name}',
    'https://getpocket.com/@{name}',
    'https://www.polyvore.com/cgi/profile?id={name}',
    'https://www.quora.com/profile/{name}',
    'https://www.reverbnation.com/{name}',
    'https://www.roblox.com/user.aspx?username={name}',
    'https://www.slideshare.net/{name}',
    'https://www.smule.com/{name}',
    'https://soundcloud.com/{name}',
    'https://www.spreaker.com/user/{name}',
    'https://steemit.com/@{name}',
    'https://stocktwits.com/{name}',
    'https://www.strava.com/athletes/{name}',
    'https://www.taringa.net/{name}',
    'https://www.threadless.com/@{name}',
    'https://tinypic.com/usermedia.php?username={name}',
    'https://www.tripadvisor.com/members/{name}',
    'https://trello.com/{name}',
    'https://www.twitch.tv/{name}',
    'https://www.ustream.tv/user/{name}',
    'https://venmo.com/{name}',
    'https://www.viadeo.com/{name}',
    'https://vk.com/{name}',
    'https://wattpad.com/user/{name}',
    'https://www.weasyl.com/~{name}',
    'https://www.weibo.com/{name}',
    'https://www.wix.com/dashboard/{name}',
    'https://www.xiami.com/u/{name}',
    'https://www.xing.com/profile/{name}',
    'https://www.yammer.com/{name}',
    'https://www.yikyak.com/user/{name}',
    'https://www.younow.com/{name}',
    'https://500px.com/{name}',
    'https://9gag.com/u/{name}',
    'https://www.academia.edu/people/search?utf8=%E2%9C%93&q={name}',
    'https://archive.org/details/@{name}',
    'https://www.audiomack.com/artist/{name}',
    'https://space.bilibili.com/{name}',
    'https://coub.com/{name}',
    'https://www.deviantart.com/{name}',
    'https://ello.co/{name}',
    'https://www.eyeem.com/u/{name}',
    'https://flavors.me/{name}',
    'https://gab.com/{name}',
    'https://hi5.com/{name}',
    'https://www.imvu.com/catalog/web_mypage.php?user={name}',
    'https://irc-galleria.net/user/{name}',
    'https://issuu.com/{name}',
    'https://www.jodel.com/user/{name}',
    'https://www.lomography.com/homes/{name}',
    'https://www.mix.com/{name}',
    'https://www.mixcloud.com/{name}',
    'https://www.myheritage.com/site-{name}',
    'https://www.netlog.com/{name}',
    'https://www.nextdoor.com/profile/{name}',
    'https://www.odnoklassniki.ru/profile/{name}',
    'https://www.orkut.com.br/Main#Profile?uid={name}',
    'https://www.pixiv.net/member.php?id={name}',
    'https://user.qzone.qq.com/{name}',
    'https://www.skyrock.com/profil/{name}',
    'https://www.soundclick.com/members/default.cfm?member={name}',
    'https://www.soup.io/remote/user/{name}',
    'https://www.tagged.com/{name}',
    'https://www.travian.com/profile.php?uid={name}',
    'https://www.twine.fm/{name}',
    'https://ello.co/{name}',
    'https://vk.com/{name}',
    'https://vsco.co/{name}',
    'https://www.wattpad.com/user/{name}',
    'https://www.weasyl.com/~{name}',
    'https://www.xanga.com/{name}',
    'https://www.yammer.com/{name}',
    'https://www.younow.com/{name}',
    'https://www.8tracks.com/{name}',
    'https://about.me/{name}',
    'https://ask.fm/{name}',
    'https://ello.co/{name}',
    'https://www.goodreads.com/{name}',
    'https://giphy.com/{name}',
    'https://www.hubpages.com/@{name}',
    'https://www.instructables.com/member/{name}',
    'https://medium.com/@{name}',
    'https://www.myspace.com/{name}',
    'https://www.pinterest.com/{name}',
    'https://profile.poshmark.com/user/{name}',
    'https://www.producthunt.com/@{name}',
    'https://www.quora.com/profile/{name}',
    'https://www.redbubble.com/people/{name}',
    'https://www.reverbnation.com/{name}',
    'https://www.scribd.com/{name}',
    'https://slides.com/{name}',
    'https://www.smashcast.tv/{name}',
    'https://www.speakerdeck.com/{name}',
    'https://www.sporcle.com/user/{name}',
    'https://www.stage32.com/{name}',
    'https://www.steamcommunity.com/id/{name}',
    'https://www.ted.com/profiles/{name}',
    'https://www.tripit.com/people/{name}',
    'https://www.tripoto.com/profile/{name}',
    'https://www.wattpad.com/user/{name}',
    'https://www.weheartit.com/{name}',
    'https://www.wix.com/{name}',
    'https://www.zhihu.com/people/{name}',
]

name = input('Enter a name: ')

for website in websites:
    url = website.replace('{name}', name)
    if check_profile(url, name):
        print(f"Profile found on {website.replace('{name}', name)}")
    else:
        print(f"No profile found on {website.replace('{name}', name)}")

#########################################
#                                       #
#   Please join my discord community:   #
#    https://discord.gg/QKJPfpaFUk      #
#                                       #
#########################################